# This is the wordup config:
# - You can customize two things here: 
# - Your wordup specific config and the config of your WordPress installation
# Documentation: https://docs.wordup.dev

# A wordup project is either of type 'plugins', 'themes' or 'installation'
type: themes
 
# The internal project name 
projectName: wordpress-test

# The slug of your project. CAUTION: You have to reinstall your dev server, when you change the slug.
slug: wordpress-test


# WordPress installation config 
wpInstall:
  title: wordpress-test
  language: en_US
  users:
    - name: admin
      password: admin
      email: test@example.com
      role: administrator
  plugins: {}
  themes: {}


